### ISSUE TITLE
Question: how best to integrate gene annotation with tidybulk?

### ISSUE THREAD

**Issue by mblue9** [jmacdon/Bioc2020Anno#2]
Hello, 

There was a question at our workshop at Bioc2020 (tidytranscriptomics) about whether there was `any intended complimentary use of tidybulk with the annotation resources described in the previous workshop` (your workshop). 

I thought it was a good question and I've made a note  [here](https://github.com/stemangiola/tidytranscriptomics/issues/1) that we could maybe add some info on how to do that to future tidybulk workshops e.g. showing how to get and add gene symbols to a *Drosophila* RNA-seq counts table (tidybulk has an `ensembl_to_symbol` function but it only works for human and mouse).

But was wondering if what I've put (below) is how you'd recommend doing this?

```
# install annotation packages for species
# BiocManager::install(c("Organism.dplyr", "TxDb.Dmelanogaster.UCSC.dm6.ensGene", "org.Dm.eg.db"))

# load library 
library(Organism.dplyr)

# get annotation
src <- src_organism("TxDb.Dmelanogaster.UCSC.dm6.ensGene")
anno_table <- tbl(src, "id") %>% 
    
    # select desired columns
    dplyr::select(ensembl, symbol) %>% 
    
    # keep one symbol per gene id 
    group_by(ensembl) %>% 
    filter(row_number()==1) %>%
    
    # convert to tibble
    collect()

# add symbols to counts table 
counts_annot <- left_join(counts_tt, anno_table, by = c("feature" = "ensembl"))
```
Cheers,
Maria

**Comment by jmacdon** [comment]
You could do that, but it's a lot of extra work, for no apparent gain. I would instead do

```
anno_table <- select(org.Dm.eg.db, keys(org.Dm.eg.db, "FLYBASE"), "SYMBOL","FLYBASE")
counts_annot <- left_join(counts_tt, anno_table, by = c("feature","FLYBASE"))
```

Unless your goal is to keep everything within the confines of the tidyverse, in which case your code does work.

**Comment by mblue9** [comment]
Ok great! Thanks for the info.
